[package]
name = "ethers-reth"
version = "0.1.0"
edition = "2021"


[dependencies]
reth-tasks = { git = "https://github.com/paradigmxyz/reth", package = "reth-tasks", rev = "f3d7988" }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc", rev = "f3d7988" }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-api", rev = "f3d7988" }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-types", rev = "f3d7988" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", package = "reth-provider", rev = "f3d7988" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", package = "reth-transaction-pool", rev = "f3d7988" }
reth-network-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-network-api", rev = "f3d7988" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", package = "reth-primitives", rev = "f3d7988" }
reth-db = { git = "https://github.com/paradigmxyz/reth", package = "reth-db", rev = "f3d7988", features = ["test-utils"] }
reth-blockchain-tree = { git = "https://github.com/paradigmxyz/reth", package = "reth-blockchain-tree", rev = "f3d7988" }
reth-beacon-consensus = { git = "https://github.com/paradigmxyz/reth", package = "reth-beacon-consensus", rev = "f3d7988" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", package = "reth-revm", rev = "f3d7988" }
reth-interfaces = { git = "https://github.com/paradigmxyz/reth", package = "reth-interfaces", rev = "f3d7988", features = ["test-utils"] }
reth-stages = { git = "https://github.com/paradigmxyz/reth", package = "reth-stages", rev = "f3d7988", features = ["test-utils"] }
reth-trie = { git = "https://github.com/paradigmxyz/reth", package = "reth-trie", rev = "f3d7988" }

# ethers
ethers = { version = "2.0.7", default-features = false, features = ["ipc", "ws", "rustls"] }



eyre = "0.6.8"
tokio = "1.28.0"
jsonrpsee = { version = "0.18", features = ["server", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1.68"
thiserror = "1.0.40"
serial_test = "2.0.0"
itertools = "0.11.0"


[patch.crates-io]
# patched for quantity U256 responses <https://github.com/recmo/uint/issues/224>
ruint = { git = "https://github.com/paradigmxyz/uint" }
revm-primitives = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
revm = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }

