[package]
name = "rethdb-middleware"
version = "0.1.0"
edition = "2021"


[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
tokio = "1.28.0"

reth-rpc = { path = "../crates/rpc/rpc" }
reth-rpc-api = { path = "../crates/rpc/rpc-api" }
reth-rpc-types = { path = "../crates/rpc/rpc-types" }
reth-provider = { path = "../crates/storage/provider" }
reth-transaction-pool = { path = "../crates/transaction-pool", features = ["test-utils"] }
reth-network-api = { path = "../crates/net/network-api", features = ["test-utils"] }
reth-primitives = { path = "../crates/primitives" }
reth-db = { path = "../crates/storage/db" }
reth-blockchain-tree = { path = "../crates/blockchain-tree" }
reth-beacon-consensus = { path = "../crates/consensus/beacon"}
reth-revm = { path = "../crates/revm"}
reth-interfaces = { path = "../crates/interfaces"}

jsonrpsee = { version = "0.18", features = ["server", "macros"] }

async-trait = "0.1.68"
thiserror = "1.0.40"



[patch.crates-io]
# patched for quantity U256 responses <https://github.com/recmo/uint/issues/224>
ruint = { git = "https://github.com/paradigmxyz/uint" }